### ISSUE TITLE
No control over accuracy

### ISSUE THREAD

**Issue by ralphrmartin** [WolframResearch/OpenCascadeLink#2]
See issue #1. There appears to be no way to control accuracy of conversions.

**Comment by ruebenko** [comment]
To the best of my knowledge OpenCascade does not provide an accuracy goal for conversions. It does, however, provide a precision control and I'll expose that. I doubt that this is useful for issue #1

**Comment by ruebenko** [comment]
Can you be a bit more specific with what you mean by 'accuracy of conversion' Do you have an example where you run of precision? Or do you, rather, want a different (finer/better) boundary conversion? I suspect the latter. For that you can use the 'LinearDeflection' option.

**Comment by ralphrmartin** [comment]
Well, in terms of the end result, the stl files I end up writing have too few facets, so that when I print the objects, the facets are obvious. Assuming I start off with some implicitly defined shape, or some built in shape like a CapsuleShape, I want to be able to control either the angular or linear error. I can now see there are options which suggest this can be done, they are not documented. Please add some simple examples of  how to use them to the documentation.

**Comment by ralphrmartin** [comment]
While there is brief discussion of the linear and angular controls in the documentation (which fails to specify units of angle) , I cannot see how to use these controls in these examples:

shape = OpenCascadeShape[CapsuleShape[{{0, -2, 0}, {0, 0, 1}}, 1]]
capsule = MeshRegion[OpenCascadeShapeSurfaceMeshToBoundaryMesh[shape]]

and

r = ImplicitRegion[x^4 + y^4 +z^4 -1 = 0, {x, y, z}];
bmesh = ToBoundaryMesh[r, {{-2, 2}, {-2, 2}, {-2, 2}}];
shape2=OpenCascadeShape[bmesh]

as neither of these involve the call to OpenCascadeShapeSurfaceMesh which has these options.

**Comment by ruebenko** [comment]
I have added the units. 
For the first issue please see this section: [OpenCascadeLink/tutorial/UsingOpenCascadeLink#1029851594](https://reference.wolfram.com/language/OpenCascadeLink/tutorial/UsingOpenCascadeLink.html#1029851594)
Please consult the ref page of [ToBoundaryMesh](https://reference.wolfram.com/language/FEMDocumentation/ref/ToBoundaryMesh.html) and or [ElementMesh generation](https://reference.wolfram.com/language/FEMDocumentation/tutorial/ElementMeshCreation.html) (there are plenty links in the tutorial) for the second issue.

**Comment by ruebenko** [comment]
There may have been an issue with the AngularDeflection in previous versions (that ship with Mathmatica 12.2) but that is fixed here already.

**Comment by ralphrmartin** [comment]
Thanks. For the second issue, I now see how to get AccuracyControl. For the  first, sorry if I am ignorant, but I am unsure how to open the link which you give. Could you please give rather fuller instructions? (I am using Wolfram Engine, so do not have access to the Help menu...)

**Comment by ruebenko** [comment]
I have made the above links point to the online documentation. That should help. You are using the "Free Wolfram Engine for Developers"?

**Comment by ralphrmartin** [comment]
Yes, I am trying to develop some 3D printing tools.

Thank you for your helpful links to the documentation. I can now control the conversions as desired.
