### ISSUE TITLE
No control over normal directions

### ISSUE THREAD

**Issue by ralphrmartin** [WolframResearch/OpenCascadeLink#3]
See issue #1. There are no options to control the normal directions (inward or outward pointing) of the shapes produced.

**Comment by ruebenko** [comment]
I have to check if OpenCascacde provides a way to change the boundary normal. For issue #1 the correct way to proceed is to fix the bug.

**Comment by ralphrmartin** [comment]
Unfortunately, all models created using this link seem to have normals in the opposite direction to that expected by other  software  in at least some circumstances (e.g. if I export as stl file, and read the resulting file with meshlab or 3D printing software). It would be useful if the normals could be flipped before / upon export. (Maybe that is an issue with stl export - I am unsure- but I cannot see how to control normals as inwards or outwards with that either).

**Comment by ralphrmartin** [comment]
Perhaps the bug workround suggested in Issue #1  would be useful in its own right as a function FlipNormals, which could be called before export.

**Comment by ruebenko** [comment]
I suspect that this is an OpenCascade 'issue'. Can you try to use `mr = MeshRegion[OpenCascadeShapeSurfaceMeshToBoundaryMesh[shape]]` and export the mesh region as STL with standard Export and see if that fixes the issue.

**Comment by ralphrmartin** [comment]
Thanks. That does indeed generate a shape with normals facing in the desired direction. Hopefully some discussion / example of this can be added to the documentation.

**Comment by ruebenko** [comment]
I have added that piece of information in the section about STL export.

**Comment by ruebenko** [comment]
You can use OpenCascadeShapeFix to fix the orientation of surfaces. This is a new open cascade function that does shape healing and among other things if automagically fixes the orientation.
