### ISSUE TITLE
Dealing with 2D cases

### ISSUE THREAD

**Issue by sgbaird** [WolframResearch/OpenCascadeLink#6]
I'm interested in meshing a segment from an image and exporting this as a STEP file, for example:
![test-segment](https://user-images.githubusercontent.com/45469701/109688460-8470ae80-7b41-11eb-9221-8cb5f4197d74.png)

Meshing the image is pretty straightforward as in:
`ToBoundaryMesh@DiscretizeRegion@ImageMesh@image`
or
`DiscretizeRegion@ImageMesh@image`

Does `OpenCascadeLink` have a way of dealing with 2D shapes? I've been playing around with it a bit and haven't found any 2D shapes that `OpenCascadeShape` seems to recognize.

The goal is to get segments in a format suitable for direct import into ANSYS (STEP or IGES and maybe one other format).

**Comment by ruebenko** [comment]
@sgbaird, access to the 2D functions have not been implemented yet. However, here is an idea you could try:

```

Needs["NDSolve`FEM`"]
Needs["OpenCascadeLink`"]

mesh = ToElementMesh[ImageMesh[img], "MeshOrder" -> 1];
coords3D = mesh["Coordinates"] /. {x_?NumericQ, y_} -> {x, y, 0.};
bmesh3D = 
  ToBoundaryMesh["Coordinates" -> coords3D, 
   "BoundaryElements" -> mesh["MeshElements"]];
shape = OpenCascadeShape[bmesh3D];
OpenCascadeShapeExport["~/test.step", shape]
```

Generate the finite element mesh from the image (img) then convert the coordinates into the 3D and generate an OC shape from it. This can be exported as a step file.

The [Catalyst conversion PDEModel application example](https://reference.wolfram.com/language/PDEModels/tutorial/MassTransport/ModelCollection/CatalystDeactivation.html) has information and examples on how to convert an image to a mesh. Maybe useful.

Also note the questions about [OpenCascadeLink on Stackexchange](https://mathematica.stackexchange.com/questions/tagged/opencascade)

**Comment by sgbaird** [comment]
Trying to add a bounding rectangle and remove the interior mesh, but running into trouble, I think with `LineElement` not being supported for 3D coords. Any thoughts?

```mathematica
<< NDSolve`FEM`
<< OpenCascadeLink`
img=Import["https://user-images.githubusercontent.com/45469701/109688460-8470ae80-7b41-11eb-9221-8cb5f4197d74.png"];
mesh=BoundaryMeshRegion@ImageMesh@img;
b=RegionBounds@mesh;
{w,h}=Differences[b\[Transpose]][[1]];
{dw,dh}=0.1{w,h};
R=Rectangle[{b[[1,1]]-dw,b[[2,1]]-dh},{b[[1,2]]+dw,b[[2,2]]+dh}];
bmesh=ToBoundaryMesh[RegionDifference[R,mesh],"MeshOrder"->1,"RegionHoles"->None];
bmesh["Wireframe"]
coords3D = bmesh["Coordinates"] /. {x_?NumericQ, y_} -> {x, y, 0.};
```

`bmesh3D=ToBoundaryMesh["Coordinates"->coords3D,"BoundaryElements"->bmesh["MeshElements"]]` 
![image](https://user-images.githubusercontent.com/45469701/122628136-a6029100-d071-11eb-8737-befe1475cc7e.png)

`bmesh3D=ToBoundaryMesh["Coordinates"->coords3D,"BoundaryElements"->bmesh["BoundaryElements"]]`
![image](https://user-images.githubusercontent.com/45469701/122628153-badf2480-d071-11eb-836b-b7a126e00fbe.png)

**Comment by ruebenko** [comment]
@sgbaird you mean like this:
```

mesh = BoundaryMeshRegion@ImageMesh@img;
b = Transpose[RegionBounds@mesh];
{w, h} = Differences[b][[1]];
{dw, dh} = 0.1 {w, h};
R = Rectangle[{b[[1, 1]] - dw, b[[1, 2]] - dh}, {b[[2, 1]] + dw, 
    b[[2, 2]] + dh}];
mesh = ToElementMesh[RegionDifference[R, mesh], "MeshOrder" -> 1, 
   "RegionHoles" -> {Total[b]/2}];
(*mesh["Wireframe"]*)

coords3D = mesh["Coordinates"] /. {x_?NumericQ, y_} -> {x, y, 0.};
bmesh3D = 
  ToBoundaryMesh["Coordinates" -> coords3D, 
   "BoundaryElements" -> mesh["MeshElements"]];
bmesh3D["Wireframe"]
```

![image](https://user-images.githubusercontent.com/11572570/122705011-27664900-d255-11eb-90f4-e5208e35bf7b.png)

**Comment by sgbaird** [comment]
Ah, just about! Just without the outer triangles either. (basically just the outline of everything, no real triangulation) The fact that you were able to get this, even, is impressive. I had been fiddling with it for a long time. Thank you for getting back so quickly.

**Comment by ruebenko** [comment]
I see. The problem with that is that I can not get OpenCascade to export a line (wire) boundary to step. You can, however, export to step if you give the object a height. Maybe that is an option for you, or you could try another export file format (DXF?) In any case here is how you could go about that.
```

Needs["OpenCascadeLink`"]
Needs["NDSolve`FEM`"]
mesh = BoundaryMeshRegion@ImageMesh@img;
b = Transpose[RegionBounds@mesh];
{w, h} = Differences[b][[1]];
{dw, dh} = 0.1 {w, h};
R = Rectangle[{b[[1, 1]] - dw, b[[1, 2]] - dh}, {b[[2, 1]] + dw, 
    b[[2, 2]] + dh}];
bmesh = ToBoundaryMesh[RegionDifference[R, mesh], "MeshOrder" -> 1, 
   "RegionHoles" -> {Total[b]/2}];
bmesh["Wireframe"]
```

![image](https://user-images.githubusercontent.com/11572570/122883003-0a0caa00-d33d-11eb-9093-e914003b053e.png)
```

coords3D = bmesh["Coordinates"] /. {x_?NumericQ, y_} -> {x, y, 0.};
incidents = ElementIncidents[bmesh["BoundaryElements"]];
(*mr=MeshRegion[coords3D,Line/@incidents]*)

lines = Line[
     coords3D[[Join[#, #[[{1}]]] &[
        DeleteDuplicates[Flatten[#]]]]]] & /@ incidents;
Graphics3D[lines, Boxed -> False]
```

![image](https://user-images.githubusercontent.com/11572570/122883082-1f81d400-d33d-11eb-8b3f-b8fa524a1efa.png)
```

wires = OpenCascadeShape /@ lines
shape = OpenCascadeShapeUnion[wires]
OpenCascadeShapeType[shape]
(* this does not work, but probably should *)
(*OpenCascadeShapeExport["~/test.step",shape]*)
shape2 = 
 OpenCascadeShapeLinearSweep[shape, {{0, 0, 0}, {0, 0, 0.1}}]
OpenCascadeShapeExport["~/test.step", shape2]
```

Two last comments: For discussions like this the [Mathematica Stackexchange site](https://mathematica.stackexchange.com/questions) is a much better place. And lastly I am curious what you want to do with the exported shape?

**Comment by ruebenko** [comment]
The issue was resolved otherwise.

**Comment by sgbaird** [comment]
Sorry, forgot to mention this was to do some finite element modeling of mechanical properties of particles and dendrites.
