### ISSUE TITLE
Why does Mathematica 10.4 load opencascade lib failed?

### ISSUE THREAD

**Issue by lavender-lee** [WolframResearch/OpenCascadeLink#7]
I would like to compile the `OpenCascadeLink` to `Mathematica 10.4` on the Windows X86-64 platform.  However, I noticed that `FindLibrary[]` cannot load the DLL.

```
libDir = NotebookDirectory[] <> "open_cascade_prebuilt\\lib"

preLoadLibs = FileNames["*.*", libDir]

LibraryLoad @ preLoadLibs[[1]]

LibraryLoad @ preLoadLibs[[2]]

(*
  ibraryFunction::load: The library E:\Open-Cascade-Link\open_cascade_prebuilt/lib\TKBin.dll cannot be loaded. 
*)

success = FreeQ[Union[LibraryLoad /@ preLoadLibs], $Failed]

LibraryLink`$LibraryError

(*
   Library load error 126: cannot find the specified
*)
```

### Screenshot

![image](https://user-images.githubusercontent.com/35004095/221364205-fe7d4d4d-0ddd-465e-9ac5-0f853ee4b6ed.png)

![image](https://user-images.githubusercontent.com/35004095/221364235-c6022857-978e-46f0-baba-b4c0f0f4ad68.png)

**Comment by ruebenko** [comment]
The oldest Mathematica version I have build OpenCascadeLink was 12.1. What you could try is to check out the earliest version of OpenCascadeLink and see if you can get that to work with M10.4 - but between 10.4 and 12.1 a lot of stuff got added and/or fixed.
