### ISSUE TITLE
Cannot open OpenCascadeLink document on Linux platform

### ISSUE THREAD

**Issue by lavender-lee** [WolframResearch/OpenCascadeLink#8]
![image](https://user-images.githubusercontent.com/35004095/224752444-00da83eb-149b-41f8-a6ca-ef4d885b5702.png)

**Comment by ruebenko** [comment]
Hm, this is odd and should not happen. I have a Linux 13.2 and do not see this problem. Perhaps this has something to do with the Chinese version. Could you please contact the wolfram support at support@wolfram.com. They will have all sorts of version and it should be possible for them to track this down.

**Comment by lavender-lee** [comment]
Anyway, Oliver, thanks for the reply. Linux system is an English version.

**Comment by ruebenko** [comment]
Hm, even more strange. Please send this to support, they should be in a position to track this down.

**Comment by ruebenko** [comment]
What happens when you call Needs["OpenCascadeLink`"] in a notebook, does that give error messages?

**Comment by lavender-lee** [comment]
It works well when I execute 

```
Needs["OpenCascadeLink`"] 

shape1 = OpenCascadeShape[Ball[{1, 0, 0}]]
shape2 = OpenCascadeShape[Ball[{0, 1/2, 0}, 1/2]]

```
